config/routes.rb
Rails.application.routes.draw do
  
  get "/search", to: "search#search"
  get 'relationships/index'
  root "homes#index"
  get "home/about" => "homes#about"
  
  
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  

    
    resources :books, only: [:create,:index,:show, :edit, :update, :destroy] do
      resources :book_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end

    resources :users, only: [:show, :edit, :index, :create, :update] do
      resource :relationships, only: [:index, :create, :destroy]
      get :follows, on: :member
      get :followers, on: :member
      # get "/followers" => "relationships#followers"
    end
  
  
  
  
  
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  
  attachment :profile_image 

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :relationships, dependent: :destroy
  # has_many :active_relationships, class_name: "Relationship"
  # has_many :passive_relationships, class_name: "Relationship"
   #フォローする側のUserから見て、フォローされる側のUserを(中間テーブルを介して)集める。なので親はfollowing_id(フォローする側)
   has_many :active_relationships, class_name: "Relationship", foreign_key: :follow_id
   # 中間テーブルを介して「follower」モデルのUser(フォローされた側)を集めることを「followings」と定義
   has_many :follows, through: :active_relationships, source: :follower
   
  
   #フォローされる側のUserから見て、フォローしてくる側のUserを(中間テーブルを介して)集める。なので親はfollower_id(フォローされる側)
   has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
   # 中間テーブルを介して「following」モデルのUser(フォローする側)を集めることを「followers」と定義
   has_many :followers, through: :passive_relationships, source: :follow
   
  
  def followed_by?(user)
    passive_relationships.where(follow_id: user.id).exists?
  end

  # validates :introduction, presence: true, length: {maximum: 50},on: :update
  # with_options on: :update do
  #   validates :introduction, presence: true, length: {maximum: 50}
  # end

  validates :introduction, presence: false, length: {maximum: 50}

  validates :name, presence: true, length: {in: 2..20}
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end
  
  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
    if @user.id == current_user.id
      render :edit
    else
      redirect_to user_path(current_user.id)
    end
  end

  def create 
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to user_path(id: current_user)
    else
      render "books/index"
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
     redirect_to user_path(@user)
     flash[:notice] = "You have updated user successfully."
    else
     render :edit
    end
  end

  def follows
    user = User.find(params[:id])
    @users = user.follows
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end

  private 
     def book_params
      params.require(:book). permit(:title, :body)
     end

     def user_params
      params.require(:user).permit(:name, :introduction, :profile_image)
     end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_templet.html.erb
<div class = "container">
 <div class = "row">
    <div class = "col-xs-3">
        <h2>User info</h2>

        <div class = "plofile-container">
            <%= attachment_image_tag @user, :profile_image, size: "100x100", fallback: "no_image.jpg", class: "img" %>
            <table class = "table"> 
                <tr><th>name</th> <th><%= @user.name %></th></tr>
                <tr><th>introduction</th><th><%= @user.introduction %></th></tr>
                <tr>
                <th>follows</th> 
                <th>
                <%= link_to follows_user_path(@user), class: "font" do %>
                    <%= @user.follows.count %>
                <% end %>
                </th>
                </tr>
                <tr>
                <th>followers</th>
                  <th>
                  <%= link_to followers_user_path(@user), class: "font" do %>
                    <%= @user.followers.count %>
                  <% end %>
                  </th>
                </tr>
                
                
           </table>
           <div class = follow>
                    <% unless @user == current_user %>
                      <% if @user.followed_by?(current_user) %>
                        <%= link_to "フォローを外す", user_relationships_path(@user.id), method: :delete, class: "btn btn-primary pull-right"  %>
                            
                      <% else %>
                        <%= link_to "フォローをする", user_relationships_path(@user.id), method: :post, class: "btn btn-danger pull-right"  %>
                            
                      <% end %>    
                      
                    <% end %>
                 </div> 

           <div class = "row">
            <% if @user.id == current_user.id %>
            <%= link_to edit_user_path(current_user.id) do %>
                <div class= " edit btn btn-outline-secondary btn-default btn-block" ><span class="glyphicon glyphicon-wrench" aria-hidden="true"></span></div>
            <% end %>
            <% end %>
           </div> 
        </div>
    
        <section class = "single-book">
        <h2>New book</h2>
         <div class = "row">  
            <%= form_for (@book) do |f| %>
            <%= f.label :title %>
            <%= f.text_field :title, class: "width" %>
            <%= f.label :body, "Opinion" %>
            <%= f.text_area :body, class: "width" %> 
        
            <%= f.submit 'Create Book', class: "btn btn-primary btn-block "  %>   
            <% end %>
         </div> 
        </section>
    </div>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
    <div class = "error">
    <h2><%= @user.errors.count %>errors prohibited this obj from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
    <% end %>
    </ul>
    </div>
  <% end %>

<div class = "container">


<h2>User info</h2>

<%= form_for(@user) do |f| %>
    <h4>name</h4>
    <%= f.text_field :name, autofocus: true, placeholder:"名前"%>
    <div class = "user-image">
    <h4>image</h4>
    <%= f.attachment_field :profile_image %>
    </div>
    <h4>introduction</h4>
    <%= f.text_area :introduction %>
    <%= f.submit "Update User" %>
<% end %>


</div>

app/views/users/followers.html.erb
<h1>followers一覧</h1>

<div class = "col-xs-12" "user-index" >
        <h2>Users</h2>
        <table class = "table">
         <thead>
            <tr>
                <th>image</th>
                <th>name</th>
            </tr>
         </thead>
         <tbody>
            <% @users.each do |user| %>
                <tr><td><%= attachment_image_tag user, :profile_image, size: "40x40", fallback: "no_image.jpg"%></td>
                <td><%= user.name %></td>
                <td><%= link_to "Show", user_path(user.id), class: "link" %></td></tr>
            <% end %>
         </tbody>   
        </table>
    </div>

app/views/users/follows.html.erb
<h1>follows一覧</h1>



    <div class = "col-xs-12" "user-index" >
        <h2>Users</h2>
        <table class = "table">
         <thead>
            <tr>
                <th>image</th>
                <th>name</th>
            </tr>
         </thead>
         <tbody>
            <% @users.each do |user| %>
                <tr><td><%= attachment_image_tag user, :profile_image, size: "40x40", fallback: "no_image.jpg"%></td>
                <td><%= user.name %></td>
                <td><%= link_to "Show", user_path(user.id), class: "link" %></td></tr>
            <% end %>
         </tbody>   
        </table>
    </div>

app/views/users/index.html.erb
<%= render "templet" %>

    <div class = "col-xs-9" "user-index" >
        <h2>Users</h2>
        <table class = "table">
         <thead>
            <tr>
                <th>image</th>
                <th>name</th>
            </tr>
         </thead>
         <tbody>
            <% @users.each do |user| %>
                <tr><td><%= attachment_image_tag user, :profile_image, size: "40x40", fallback: "no_image.jpg"%></td>
                <td><%= user.name %></td>
                <td>フォロー数　<%= user.follows.count %></td>
                <td>フォロワー数 <%= user.followers.count %></td>
                
                <td>
                <% unless user == current_user %>
                    <% if user.followed_by?(current_user) %>
                    <%= link_to "フォローを外す", user_relationships_path(user.id), method: :delete, class: "link"  %>
                        
                    <% else %>
                    <%= link_to "フォローをする", user_relationships_path(user.id), method: :post, class: "link"  %>
                        
                    <% end %>  
                <% end %>      
                </td>
                <td><%= link_to "Show", user_path(user.id), class: "link" %></td>
                 
                </tr>
            <% end %>
         </tbody>   
        </table>
    </div>

</div> 
</div>

app/views/users/show.html.erb
<% if flash[:notice] %>
    <%= flash[:notice] %>
<% end %>    

<%= render "templet" %>


<div class ="col-xs-9">
<h2>Books</h2>
    <table class = "table">
        <thead>
        <tr> 
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
        </tr>
         </thead>
         <tbody>
         <% @books.each do |book| %>
            <tr>
                <td>
                <%= link_to user_path(@user) do %>
                <%= attachment_image_tag @user, :profile_image, size: "40x40", fallback: "no_image.jpg"%>
                <% end %>
                </td>
                <td><%= link_to book.title, book_path(book.id), class: "link" %></td>
                <td><%= book.body %></td>
            </tr>
            <% end %>
         </tbody>   
    </table>


 </div> 
</div>