config/routes.rb
Rails.application.routes.draw do
  
  get "/search", to: "search#search"
  get 'relationships/index'
  root "homes#index"
  get "home/about" => "homes#about"
  
  
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  

    
    resources :books, only: [:create,:index,:show, :edit, :update, :destroy] do
      resources :book_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end

    resources :users, only: [:show, :edit, :index, :create, :update] do
      resource :relationships, only: [:index, :create, :destroy]
      get :follows, on: :member
      get :followers, on: :member
      # get "/followers" => "relationships#followers"
    end
  
  
  
  
  
  
end

app/models/book.rb
class Book < ApplicationRecord

   belongs_to :user
   has_many :favorites, dependent: :destroy
   has_many :book_comments, dependent: :destroy

   validates :title, presence: true
   validates :body, presence: true, length: {maximum: 200}

   def favorited_by?(user)
      favorites.where(user_id: user.id).exists?
   end
    
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :authenticate_user!
    def create 
        @user = current_user
        flash[:notice] = "You have creatad book successfully."
        @books = Book.all
        @book = Book.new(book_params)
        @book.user_id = current_user.id
        if @book.save
            redirect_to book_path(@book.id)
        else
            render "books/index"
        end
    end

    def index
        @user = current_user
        @book = Book.new
        @books = Book.all
        
    end

    def show
        @bookcreate = Book.find(params[:id]) 
        @user = @bookcreate.user
        @book = Book.new
        @books = Book.all
        @book_comment = BookComment.new
    end

    def edit
        @book = Book.find(params[:id])
        if @book.user == current_user
            render "edit"
          else
            redirect_to books_path
          end
    end

    def update
        @book = Book.find(params[:id])
        flash[:notice] = "You have updated user successfully."
        if @book.update(book_params)
            redirect_to book_path(@book.id)
            flash[:notice] = "You have updated user successfully."
           else
            render :edit
         end
    end

    def destroy
        book = Book.find(params[:id])
        book.destroy
        redirect_to books_path
    end

    private 
     def book_params
        params.require(:book).permit(:title, :body)
     end

end

app/views/books/_new.html.erb
<section class = "single-book">
<%= form_for (@book) do |f| %>
   <h2>Title</h2>
   <%= f.text_field :title %>
   <h2>Opinion</h2>
   <%= f.text_area :body %> 

   <%= f.submit '投稿' %>
<% end %>
</section>

app/views/books/edit.html.erb
<% if @book.errors.any? %>
    <div class = "error">
    <h2><%= @book.errors.count %>errors prohibited this obj from being saved:</h2>
    <ul>
    <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
    <% end %>
    </ul>
    </div>
  <% end %>

<div class = "container">
    <div class = "row">
    <div class = "editcontainer row-md-6 col-md-offset-3">
    <h1>Editing Book</h1>

    <%= form_for(@book) do |f| %>
        <h4>Title</h4>
         <%= f.text_field :title, class: "area" %>
        <h4>Opinion</h4>
         <%= f.text_area :body, class: "area" %>
         <%= f.submit 'Update Book',class: "btn btn-primary btn-block" %>
    <% end %>
    <%= link_to "Show", book_path(@book.id) %> | 
    <%= link_to "Back", books_path %>
    </div>
    </div>
</div>

app/views/books/index.html.erb
  <% if @book.errors.any? %>
    <div class = "error">
    <h2><%= @book.errors.count %>errors prohibited this obj from being saved:</h2>
    <ul>
    <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
    <% end %>
    </ul>
    </div>
  <% end %>

  <%= render "users/templet" %>
 
 
 <div class ="col-xs-9">
 <h2>Books</h2>
 
     <table class = "table">
         <thead>
         <tr>   
            <th></th>
             <th>Title</th>
             <th>Opinion</th>
         </tr>
          </thead>
          <tbody>
          <% @books.each do |book| %>
             <tr>
             <td>
             <%= link_to user_path(book.user) do %>
             <%= attachment_image_tag book.user, :profile_image, size: "40x40", fallback: "no_image.jpg"%>
             <% end %>
             </td>
                 <td><%= link_to book.title, book_path(book.id), class: "link" %></td>
                 <td><%= book.body %></td>
            <td>
            <% if book.favorited_by?(current_user) %>
                <%= link_to book_favorites_path(book), method: :delete, class: "font" do %>
                    <i class="glyphicon glyphicon-heart" aria-hidden="true" style="color: block;"></i>  
                    <%= book.favorites.count %> 
                <% end %>
            <% else %>
            <%= link_to book_favorites_path(book), method: :post, class: "font" do %>
                <i class="glyphicon glyphicon-heart-empty" aria-hidden="true"  ></i>  
                <%= book.favorites.count %>
            <% end %>      
            <% end %>
           </td>
           <td>
           <span>コメント数：　<%= book.book_comments.count %></span>
           </td>
            </tr>
             <% end %>
          </tbody>   
     </table>
 
 
  </div> 
 </div>

app/views/books/show.html.erb
<% if flash[:notice] %>
    <%= flash[:notice] %>
<% end %>  

<%= render "users/templet" %>


<div class ="col-xs-9">

    <table class = "table">
    <thead>
        <h2>Book detail</h2>
    </thead>        
         <tbody>
         
            <td>
                <%= attachment_image_tag @user, :profile_image, size: "40x40", fallback: "no_image.jpg"%><br>
                <%= link_to @user.name, user_path(@user.id), class: "link" %>
            </td>   
            <td>
                <%= link_to @bookcreate.title, book_path(@bookcreate.id), class: "link" %>
            </td>
            <td>
                <%= @bookcreate.body %>
            </td>
        <% if @bookcreate.user == current_user %> 
           <td> 
            <%= link_to edit_book_path(@bookcreate.id) do %>
                <button type="button" class="btn btn-success active">Edit</button>
            <% end %>
           </td>
           <td> 
            <%= link_to book_path(@bookcreate.id), method: :delete do %>
                <button type="button" class="btn btn-danger active">Destroy</button>
            <% end %>
           </td>
        <% end %>
           <td>
            <% if @bookcreate.favorited_by?(current_user) %>
                <%= link_to book_favorites_path(@bookcreate), method: :delete, class: "font" do %>
                    <i class="glyphicon glyphicon-heart" aria-hidden="true" style="color: block;"></i>  
                    <%= @bookcreate.favorites.count %> 
                <% end %>
            <% else %>
            <%= link_to book_favorites_path(@bookcreate), method: :post, class: "font" do %>
                <i class="glyphicon glyphicon-heart-empty" aria-hidden="true"  ></i>  
                <%= @bookcreate.favorites.count %>
                <% end %>      
            <% end %>
           </td>
           <td>
              <span>コメント数：　<%= @bookcreate.book_comments.count %></span>
           </td>
          
          
         </tbody>   
    </table>

    <table class = "table">
    
    <% @bookcreate.book_comments.each do |bookcreate| %> 
        <tr>
        <td class = "com col-xs-2">
        <%= attachment_image_tag bookcreate.user, :profile_image, size: "40x40", fallback: "no_image.jpg"%><br>
        <%= link_to bookcreate.user.name, user_path(@user.id), class: "link" %>
        </td>
        <td>
        <%= bookcreate.comment %>   
        </td>
        <td>
        <% if bookcreate.user_id == current_user.id %>
            <%= link_to "delete", book_book_comment_path(bookcreate.book_id, bookcreate), method: :delete, class: "btn btn-danger pull-right" %>
        <% end %>
        <td>
        </tr>
    <% end %> 
     
    </table>

    <div class = "comment">
      <%= form_for [@bookcreate,@book_comment] do |f| %>
        <div class = "col-xs-9">
            <%= f.text_area :comment, class: "col-xs-12 comment_heigth" %>
        </div>
        <div class = "col-xs-3">
            <%= f.submit "送信" %>
        </div>
      <% end %>
    </div>


 </div> 
</div>