config/routes.rb
Rails.application.routes.draw do
  
  get "/search", to: "search#search"
  get 'relationships/index'
  root "homes#index"
  get "home/about" => "homes#about"
  
  
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  

    
    resources :books, only: [:create,:index,:show, :edit, :update, :destroy] do
      resources :book_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end

    resources :users, only: [:show, :edit, :index, :create, :update] do
      resource :relationships, only: [:index, :create, :destroy]
      get :follows, on: :member
      get :followers, on: :member
      # get "/followers" => "relationships#followers"
    end
  
  
  
  
  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

   belongs_to :user
   has_many :favorites, dependent: :destroy
   has_many :book_comments, dependent: :destroy

   validates :title, presence: true
   validates :body, presence: true, length: {maximum: 200}

   def favorited_by?(user)
      favorites.where(user_id: user.id).exists?
   end
    
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
    belongs_to :user
    belongs_to :book

    validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :follow, class_name: "User"
    belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  
  attachment :profile_image 

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :relationships, dependent: :destroy
  # has_many :active_relationships, class_name: "Relationship"
  # has_many :passive_relationships, class_name: "Relationship"
   #フォローする側のUserから見て、フォローされる側のUserを(中間テーブルを介して)集める。なので親はfollowing_id(フォローする側)
   has_many :active_relationships, class_name: "Relationship", foreign_key: :follow_id
   # 中間テーブルを介して「follower」モデルのUser(フォローされた側)を集めることを「followings」と定義
   has_many :follows, through: :active_relationships, source: :follower
   
  
   #フォローされる側のUserから見て、フォローしてくる側のUserを(中間テーブルを介して)集める。なので親はfollower_id(フォローされる側)
   has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
   # 中間テーブルを介して「following」モデルのUser(フォローする側)を集めることを「followers」と定義
   has_many :followers, through: :passive_relationships, source: :follow
   
  
  def followed_by?(user)
    passive_relationships.where(follow_id: user.id).exists?
  end

  # validates :introduction, presence: true, length: {maximum: 50},on: :update
  # with_options on: :update do
  #   validates :introduction, presence: true, length: {maximum: 50}
  # end

  validates :introduction, presence: false, length: {maximum: 50}

  validates :name, presence: true, length: {in: 2..20}
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :authenticate_user!
    def create 
        @user = current_user
        flash[:notice] = "You have creatad book successfully."
        @books = Book.all
        @book = Book.new(book_params)
        @book.user_id = current_user.id
        if @book.save
            redirect_to book_path(@book.id)
        else
            render "books/index"
        end
    end

    def index
        @user = current_user
        @book = Book.new
        @books = Book.all
        
    end

    def show
        @bookcreate = Book.find(params[:id]) 
        @user = @bookcreate.user
        @book = Book.new
        @books = Book.all
        @book_comment = BookComment.new
    end

    def edit
        @book = Book.find(params[:id])
        if @book.user == current_user
            render "edit"
          else
            redirect_to books_path
          end
    end

    def update
        @book = Book.find(params[:id])
        flash[:notice] = "You have updated user successfully."
        if @book.update(book_params)
            redirect_to book_path(@book.id)
            flash[:notice] = "You have updated user successfully."
           else
            render :edit
         end
    end

    def destroy
        book = Book.find(params[:id])
        book.destroy
        redirect_to books_path
    end

    private 
     def book_params
        params.require(:book).permit(:title, :body)
     end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    def create
        # @book = Book.find(params[:id])
        book = Book.find(params[:book_id])
        favorite = current_user.favorites.new(book_id: book.id)
        favorite.save
        redirect_back(fallback_location: request.path)
    end

    def destroy
        book = Book.find(params[:book_id])
        favorite = current_user.favorites.find_by(book_id: book.id)
        favorite.destroy
        redirect_back(fallback_location: request.path)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    
  end

  def about
  end

  
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    @model = params["search"]["model"]
    @content = params["search"]["content"]
    @how = params["search"]["how"]
    @dates = search_for(@how,@model,@content)
  end

  private
  def match(model,content)
    if model == "user"
      User.where(name: content)
    elsif model == "book"
      Book.where(title: content)
    end
  end

  def forward(model,content)
    if model == "user"
      User.where("name LIKE?", "#{content}%")
    elsif model == "book"
      Book.where("title LIKE?", "#{content}%")
    end
  end

  def partical(model,content)
    if model == "user"
      User.where("name LIKE?", "%#{content}%")
    elsif model == "book"
      Book.where("title LIKE?", "%#{content}%")
    end
  end

  def search_for(how,model,content)
  case how
  when "match"
    match(model,content)
  when "forword"
    forward(model,content)
  when "backward"
    backward(model,content)
  when "partical"
    partical(model,content)
  end
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end
  
  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
    if @user.id == current_user.id
      render :edit
    else
      redirect_to user_path(current_user.id)
    end
  end

  def create 
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to user_path(id: current_user)
    else
      render "books/index"
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
     redirect_to user_path(@user)
     flash[:notice] = "You have updated user successfully."
    else
     render :edit
    end
  end

  def follows
    user = User.find(params[:id])
    @users = user.follows
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end

  private 
     def book_params
      params.require(:book). permit(:title, :body)
     end

     def user_params
      params.require(:user).permit(:name, :introduction, :profile_image)
     end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/book_creates_helper.rb
module BookCreatesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/mypages_helper.rb
module MypagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  

  <div class = "header">
  <nav class="navbar navbar-default navbar-static-top">
	<div class= "container">
		<div class="navbar-header">
			<span>
				Bookers
			</span>
		</div>
		
		<div class= "navbar-right" >
    <ul class="nav navbar-nav">
     <% if user_signed_in? %>
      <li>
      <%= link_to user_path(current_user.id) do %>
        <span class = "glyphicon glyphicon-home" aria-hidden="true"></span>   Home
      <% end %>  
      </li>
      <li>
      <%= link_to users_path do %>
        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>   Users
      <% end %>
      </li>
      <li>
      <%= link_to books_path do %>
      <span class="glyphicon glyphicon-book" aria-hidden="true"></span>  Books
      <% end %>
      </li>
      <li>
      <%= link_to destroy_user_session_path, method: :delete do %>
      <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span> logout
      <% end %>
      </li>
     <% else %>
      <li> <span class = "glyphicon glyphicon-home" aria-hidden="true"><a href = "/"> Home</a></span></li>
      <li> <span class = "glyphicon glyphicon-paperclip" aria-hidden="true"> <a href = "/home/about"> About</a></span></li>
      <li>  <span class = "glyphicon glyphicon-edit" aria-hidden="true"><%= link_to ' sign up', new_user_registration_path %></span></li>
      <li> <span class = "glyphicon glyphicon-log-in" aria-hidden="true" ><%= link_to ' login', new_user_session_path %></span></li>
     <% end %>
     </ul>
			
		</div>
	</div>
  </nav>
  </div>
  
  
  <div class = "col-xs-12"> 
  <div class = "col-xs-6 block-center">
  <% if user_signed_in? %> 
  <%= form_tag(search_path, method: :get) do %>
    <%= text_field_tag "search[content]" %>
    <%= select_tag "search[model]",options_for_select({"User" => "user", "Book" => "book"}) %>
    <%= select_tag "search[how]", options_for_select({"完全一致" => "match", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partical"}) %>
    <%= submit_tag "検索" %>
  <% end %>  
  <% end %>
  </div>
  </div>
  
  

    <%= yield %>

    <div class = "footer col-xs-3 col-xs-offset-9">
    <p>CopyRight Infratop.inc</p>
    </div>
  </body>
</html>